"""initial

Revision ID: 1882872df520
Revises: 
Create Date: 2023-05-22 11:27:14.954156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1882872df520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('pissoir', sa.Boolean(), nullable=True),
    sa.Column('toilet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toilet_building'), ['building'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_pissoir'), ['pissoir'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_room'), ['room'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_toilet'), ['toilet'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toilet_toilet'))
        batch_op.drop_index(batch_op.f('ix_toilet_room'))
        batch_op.drop_index(batch_op.f('ix_toilet_pissoir'))
        batch_op.drop_index(batch_op.f('ix_toilet_gender'))
        batch_op.drop_index(batch_op.f('ix_toilet_floor'))
        batch_op.drop_index(batch_op.f('ix_toilet_building'))

    op.drop_table('toilet')
    # ### end Alembic commands ###
