"""empty message

Revision ID: d918218671f8
Revises: b9a5e3691988
Create Date: 2022-12-01 10:06:17.096469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd918218671f8'
down_revision = 'b9a5e3691988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('pissoir', sa.Boolean(), nullable=True),
    sa.Column('toilet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toilet_building'), ['building'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_pissoir'), ['pissoir'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_room'), ['room'], unique=False)
        batch_op.create_index(batch_op.f('ix_toilet_toilet'), ['toilet'], unique=False)

    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.drop_index('ix_number_value')

    op.drop_table('number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.create_index('ix_number_value', ['value'], unique=False)

    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toilet_toilet'))
        batch_op.drop_index(batch_op.f('ix_toilet_room'))
        batch_op.drop_index(batch_op.f('ix_toilet_pissoir'))
        batch_op.drop_index(batch_op.f('ix_toilet_floor'))
        batch_op.drop_index(batch_op.f('ix_toilet_building'))

    op.drop_table('toilet')
    # ### end Alembic commands ###
