"""empty message

Revision ID: edb31dc45747
Revises: 
Create Date: 2022-11-29 13:57:55.122779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb31dc45747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_number'), ['number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_number_number'))

    op.drop_table('number')
    # ### end Alembic commands ###
